### ISSUE TITLE
Can You please upload your trained file to your repository?

### ISSUE THREAD

**Issue by vishal2612200** [ljanyst/traffic-lights-detector#2]
It will be really helpful if you can upload inference_graph.pb  file to your repository. Please upload checkpoint and model.ckpt file also or You can upload your whole training folder on your repository , it will really helpful for user.

**Comment by ljanyst** [comment]
Sorry, but no. This was a Udacity project and making those things available would facilitate plagiarism too much. It's easy enough to reproduce the results with your own data.

**Comment by vishal2612200** [comment]
okay no problem, thanks for the support.
